services:
  devtools:
    build: .
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
      - node_modules_backend:/workspace/backend/node_modules
      - node_modules_frontend:/workspace/frontend/node_modules
    restart: always
    tty: true

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./database/data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
      - node_modules_backend:/backend/node_modules
    ports:
      - 3000:3000
    restart: always
    command: bash -c 'if [ ! -f ".env" ]; then cp ".env.sample" ".env"; fi && npm run db-push && npm run dev'
    depends_on:
      - database

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - node_modules_frontend:/frontend/node_modules
    ports:
      - 5173:5173
    restart: always
    command: bash -c 'if [ ! -f ".env" ]; then cp ".env.sample" ".env"; fi && npm run dev -- --host'

volumes:
  node_modules:
  node_modules_backend:
  node_modules_frontend:
