services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./database/data:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - node_modules_backend:/app/backend/node_modules
    ports:
      - 3000:3000
    restart: always
    command: bash -c "npx prisma db push && npm run dev"
    depends_on:
      - database

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - node_modules_frontend:/app/frontend/node_modules
    ports:
      - 5173:5173
    command: npm run dev -- --host
    depends_on:
      - database
      - backend

volumes:
  node_modules_backend:
  node_modules_frontend:
