services:
  devtools:
    build: .
    volumes:
      - .:/app
      - node_modules_app:/app/node_modules
      - node_modules_backend:/app/backend/node_modules
      - node_modules_frontend:/app/frontend/node_modules
      - node_modules_types:/app/packages/types/node_modules
      - node_modules_score:/app/packages/score/node_modules
      - node_modules_question_sets:/app/packages/question-sets/node_modules
      - node_modules_api_types:/app/packages/api-types/node_modules
      - dist_types:/app/packages/types/dist
      - dist_score:/app/packages/score/dist
      - dist_question_sets:/app/packages/question-sets/dist
      - dist_api_types:/app/packages/api-types/dist
    tty: true

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./database/data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - .:/app
      - node_modules_backend:/app/backend/node_modules
      - node_modules_types:/app/packages/types/node_modules
      - node_modules_score:/app/packages/score/node_modules
      - node_modules_question_sets:/app/packages/question-sets/node_modules
      - node_modules_api_types:/app/packages/api-types/node_modules
      - dist_types:/app/packages/types/dist
      - dist_score:/app/packages/score/dist
      - dist_question_sets:/app/packages/question-sets/dist
      - dist_api_types:/app/packages/api-types/dist
    ports:
      - 3000:3000
    command: bash -c 'cd backend && if [ ! -f ".env" ]; then cp ".env.sample" ".env"; fi && npm run db-push && npm run dev'
    depends_on:
      - database
    restart: on-failure

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - .:/app
      - node_modules_frontend:/app/frontend/node_modules
      - node_modules_types:/app/packages/types/node_modules
      - node_modules_score:/app/packages/score/node_modules
      - node_modules_question_sets:/app/packages/question-sets/node_modules
      - node_modules_api_types:/app/packages/api-types/node_modules
      - dist_types:/app/packages/types/dist
      - dist_score:/app/packages/score/dist
      - dist_question_sets:/app/packages/question-sets/dist
      - dist_api_types:/app/packages/api-types/dist
    ports:
      - 5173:5173
    command: bash -c 'cd frontend && if [ ! -f ".env" ]; then cp ".env.sample" ".env"; fi && npm run dev -- --host'

volumes:
  node_modules_app:
  node_modules_backend:
  node_modules_frontend:
  node_modules_types:
  node_modules_score:
  node_modules_question_sets:
  node_modules_api_types:
  dist_types:
  dist_score:
  dist_question_sets:
  dist_api_types:
