services:
  devtools:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: tail -f /dev/null

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./database/data:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
      - node_modules_backend:/backend/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - database

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - node_modules_frontend:/frontend/node_modules
    ports:
      - 5173:5173
    command: npm run dev -- --host

volumes:
  node_modules:
  node_modules_backend:
  node_modules_frontend:
