services:
  - type: web
    name: typing-game
    env: static
    # rootDir: frontend
    # buildCommand: npm install && npm run build
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /
  - type: web
    name: typing-game-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
