services:
  - type: web
    name: typing-game
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /
    envVars:
      - key: VITE_API_ENDPOINT
        value: https://typing-game-backend.onrender.com
  - type: web
    name: typing-game-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: WEB_ORIGIN
        value: https://typing-game.onrender.com
