name: Format

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Run format
        run: npm run format:check
        shell: bash
